include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
analyzer:
  exclude:
    - "**.g.dart"
    - "**.gen.dart"
    - "packages/*"
    - "assets/*"
