name: trueme
description: "True.me"
publish_to: 'none'
version: 1.10.1+60

environment:
  sdk: ^3.5.3

dependencies:
  auth0_flutter: ^1.2.1
  auto_route: ^7.7.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.5
  flutter_tts: ^4.2.2
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^8.0.0
  http: ^1.2.2
  injectable: ^2.5.0
  intl: ^0.20.2
  logging: ^1.3.0
  mixpanel_flutter: ^2.3.1
  onesignal_flutter: ^5.0.4
  package_info_plus: ^8.3.0
  result_dart: ^1.1.1
  sentry_flutter: ^8.3.1
  shared_preferences: ^2.5.2
  showcaseview: ^4.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^7.2.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.7
  flutter_gen_runner: # Added proper version
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.5.0
  json_serializable: ^6.6.2
  melos: ^6.2.0
  mocktail: ^1.0.4
  network_image_mock: ^2.0.1
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#000000"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter_native_splash:
  image: assets/logo/logo.png
  color: "#000000"
  android: true
  ios: true
  android_12:
    color: "#000000"
    icon_background_color: "#000000"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/svg/
    - assets/png/
    - assets/keys/develop/api_keys.json
    - assets/keys/production/api_keys.json
