-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDJEaeRZn3pEeqLFP
LcVvd3UIjJsP35wPE8sVcFhJuRCgCgYIKoZIzj0DAQehRANCAATvvnSZB/oiu4k4
lddDOMnLQvXxsJmn9U+FkjGuaclJmxN0jZ3B7yy4KPbTqDpPMPHgVrNQ0uttpvv0
2NAOTyYy
-----END PRIVATE KEY-----